# Generated by Django 6.0.7 on 2026-07-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='map_link',
        ),
        migrations.AddField(
            model_name='event',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/'),
        ),
        migrations.AddField(
            model_name='event',
            name='map_pin_x',
            field=models.FloatField(blank=True, help_text='Pin X position as percentage', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='map_pin_y',
            field=models.FloatField(blank=True, help_text='Pin Y position as percentage', null=True),
        ),
    ]
