# Generated by Django 6.0.7 on 2026-07-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_map_link_event_map_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='map_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='map_pin_x',
        ),
        migrations.RemoveField(
            model_name='event',
            name='map_pin_y',
        ),
        migrations.AddField(
            model_name='event',
            name='map_latitude',
            field=models.FloatField(blank=True, help_text='Latitude for event pin', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='map_longitude',
            field=models.FloatField(blank=True, help_text='Longitude for event pin', null=True),
        ),
    ]
