# Generated by Django 6.0.7 on 2026-08-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_profile_dob_profile_father_name_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('tech_fest', 'Tech Fest'), ('cultural', 'Cultural'), ('hackathons', 'Hackathons'), ('seminars', 'Seminars'), ('competitions', 'Competitions'), ('others', 'Others')], default='others', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='subcategory',
            field=models.CharField(choices=[('internships', 'Internships'), ('jobs', 'Jobs'), ('competitions', 'Competitions'), ('mock_tests', 'Mock Tests'), ('mentorships', 'Mentorships'), ('courses', 'Courses'), ('interviews', 'Interviews'), ('hundred_days_to', '100 Days to'), ('others', 'Others')], default='others', max_length=30),
        ),
    ]
