# Generated by Django 6.0.7 on 2026-08-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_event_type_event_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='registration_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='registration_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
