# Generated by Django 6.0.7 on 2026-08-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventmember_registration_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/qr_codes/'),
        ),
    ]
