# Generated by Django 6.0.7 on 2026-08-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('notification', 'Notification'), ('message', 'Message')], default='notification', max_length=20),
        ),
    ]
