# Generated by Django 6.0.7 on 2026-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_resource_sponsor_vendor_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organizer',
            field=models.BooleanField(default=False, help_text='Organizers can access admin features'),
        ),
    ]
