# Generated by Django 6.0.7 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_is_organizer_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10),
        ),
    ]
