# Generated by Django 6.1 on 2026-09-02 16:32

import django.db.models.deletion
import mongo_apps
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_approvalrequest_id_alter_budgetitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', mongo_apps.MongoObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='events.eventmember')),
            ],
            options={
                'ordering': ['attendance_date'],
                'unique_together': {('event_member', 'attendance_date')},
            },
        ),
    ]
